name: Android Build 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Login to Expo (requires EXPO_TOKEN secret)
        uses: expo/expo-github-action@v1
        with:
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Android App
        uses: expo/expo-github-action@v1
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          platform: android

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        if: ${{ success() }}
        with:
          name: android-build
          path: android/app/build/outputs/apk/release/app-release.apk
